<<<<<<< HEAD
# Generated by Django 4.1 on 2023-05-20 15:09
=======
# Generated by Django 4.2 on 2023-05-20 15:44
>>>>>>> ce6fede72165cef0c2dc36d928d807dbe47ea16d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMensajeros', '0001_initial'),
        ('GestionClientes', '0009_remove_user_propietariocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mensajeros',
            field=models.ManyToManyField(to='GestionMensajeros.mensajeros'),
        ),
    ]
