# Generated by Django 4.2 on 2023-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleestadopedido',
            name='fecha_hora',
            field=models.DateField(),
        ),
    ]
