# Generated by Django 4.2 on 2023-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0002_alter_detalleestadopedido_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleestadopedido',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='detalleestadopedido',
            name='foto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
