# Generated by Django 4.2 on 2023-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0003_alter_detalleestadopedido_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleestadopedido',
            name='foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
