# Generated by Django 4.2 on 2023-06-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0004_alter_detalleestadopedido_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleestadopedido',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='detalles_estado'),
        ),
    ]
