# Generated by Django 4.2 on 2023-06-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0006_pedido_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
